<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>WorldClock</AssemblyName>
    <RootNamespace>WorldClock</RootNamespace>
    <Version>1.1.0</Version>
    <Copyright>Copyright (c) 2026 Brendon. MIT License.</Copyright>
  </PropertyGroup>

</Project>
